# yaml configuration file for linker/loader of Co-RTOS
# yaml 10 minutes tutorial:
#   https://www.youtube.com/watch?v=cdLNKUoMc6c

Hardware:
  Processor:
    # Required: Number of cores and threads per core.
    Cores: 1
    ThreadsPerCore: 1
    ISA: 32 # 32/64 bit (Default: 32)

  Memory:
    MaxPhysicalAddrBitWidth: 36
    Flash:
      StartAddr: 0x0  # physical address
      # EndAddr: ...
      # SizeInBytes: ...
      # SizeInKiloBytes: ...
      SizeInMegaBytes: 16
      Permissions: RXC  # (Read,Write,eXecute,Cacheable)
    RAM:
      StartAddr: 0x40000000
      # EndAddr: ...
      # SizeInBytes: ...
      SizeInMegaBytes: 64
      Permissions: RWXC
    NCRAM:
      StartAddr: 0x50008000  # physical address
      # SizeInBytes: ...
      SizeInKiloBytes: 224
      Permissions: RW
    MMIO: # Memory Mapped IO
      StartAddr: 0xFF000000  # physical address
      EndAddr:   0xFFFFFFFF
      # SizeInBytes: ...
      # SizeInKiloBytes: ...
      # SizeInKiloBytes: 4
      Permissions: RW

  # see ./AjitPublicResources/tools/ajit_access_routines_mt/include/device_addresses.h
  Devices:
    - Name: Timer
      MemoryRegion:
        StartAddr: 0xFFFF3100 # physical address (in MMIO)
        SizeInBytes: 256 # 16x16
        Permissions: RW
      NamedRegisters:
        Control: 0xFFFF3100
    - Name: InterruptController
      MemoryRegion:
        StartAddr: 0xFFFF3000
        SizeInBytes: 32
        Permissions: RW
      NamedRegisters:
        Control: 0xFFFF3000
    - Name: Serial
      MemoryRegion:
        StartAddr: 0xFFFF3200
        SizeInBytes: 64
        Permissions: RW
      NamedRegisters:
        Control: 0xFFFF3200
        TX: 0xFFFF3204
        RX: 0xFFFF3208
    - Name: ScratchArea
      MemoryRegion:
        StartAddr: 0xFFFF2C00
        SizeInBytes: 1024
        Permissions: RW
    - Name: NIC
      MemoryRegion:
        StartAddr: 0xFF000000
        SizeInBytes: 1024 # 256 * 4 bytes
        Permissions: RW
Software:
  BuildAndExecute:
    # Optional: Specify the log level. Default is NONE.
    # ALL < TRACE < DEBUG < INFO < ERROR < CRITICAL < NONE
    LogLevel: DEBUG
    OptimizationLevel: 2 # i.e. O2 (Accepted values: 0, 1, 2)
    # specify argument string for C compiler......
    EnableSerial: Yes # Yes/No (Default: Yes)
    Debug: No # Yes/No (Default: No)
    FirstDebugPort: 8888
    BuildArgs: "-D USE_CORTOS -D USE_VMAP -D CLK_FREQUENCY=80000000 
    -c $AJIT_HOME/AI_NIC_DEMO/lwip/Caching_app/main.c
    -I $AJIT_HOME/AI_NIC_DEMO/lwip/Caching_app/include
    -I $AJIT_HOME/AI_NIC_DEMO/lwip/Caching_app/include/arch
    -I $AJIT_HOME/AI_NIC_DEMO/lwip/lwip/src/include
    -I $AJIT_HOME/AI_NIC_DEMO/Networking/NIC_1.1/driver/include
    -I $AJIT_HOME/application_development/rng_marsaglia/include
    -I $AJIT_HOME/AI_NIC_DEMO/lwip/Caching_app/tcp_app
    -C $AJIT_HOME/AI_NIC_DEMO/lwip/Caching_app/tcp_app	
    -C $AJIT_HOME/application_development/rng_marsaglia/src
    -C $AJIT_HOME/AI_NIC_DEMO/Networking/NIC_1.1/driver/src
    -c $AJIT_HOME/AI_NIC_DEMO/lwip/lwip/src/netif/ethernet.c
    -c $AJIT_HOME/AI_NIC_DEMO/lwip/lwip/src/api/err.c 
    -C $AJIT_HOME/AI_NIC_DEMO/lwip/lwip/src/core 
    -C $AJIT_HOME/AI_NIC_DEMO/lwip/lwip/src/core/ipv4
    -C $AJIT_HOME/AI_NIC_DEMO/lwip/Caching_app/src"

  # Required: Which functions execute on each ajit thread.
  ProgramThreads:
    - CortosInitCalls:
        - main
  # One can also specify an infinite loop on the function:
  #   CortosLoopCalls:
  #     - main1
      StackSize:
        SizeInKiloBytes: 2048

  DynamicMemory: # Dynamic Memory Configuration.
    # SizeInBytes: ...
# 32MB + 24 KB
    SizeInKiloBytes: 32792
    # SizeInMegaBytes: 32

  Locks: # Locks for synchronization between threads.
#      Cacheable: 32
     NonCacheable: 32
#
#   MessageQueues: # List of queues in the system.
#     - QueueIdStart: 0    # goes to QueueIdStart+NumOfQueues-1
#       NumOfQueues: 32
#       MessageSizeInBytes: 32
#       TotalMessageCapacity: 32 # num. of messages
#
#     - QueueIdStart: 32    # goes to QueueIdStart+NumOfQueues-1
#       NumOfQueues: 16
#       MessageSizeInBytes: 8
#       TotalMessageCapacity: 256 # num. of messages
#
     # interrupt handler for timer.
#  Interrupts: # hardware interrupts
#    - Index: 10 # timer
#      Function: my_timer_interrupt_handler

